apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.12.0
          ports:
            - containerPort: 5601
          env:
            - name: KIBANA_SYSTEM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: kibana_password
          readinessProbe:  # Adjusted this section
            httpGet:
              path: /
              port: 5601
            initialDelaySeconds: 60  # Increased delay
            periodSeconds: 10
            timeoutSeconds: 5
          lifecycle:  # Startup delay to ensure Elasticsearch is ready
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 120"]  # Kibana waits 120s before starting
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: kibana
