apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    spec:
      containers:
      - name: setup
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
        command: ["/bin/bash", "/entrypoint.sh"]
        env:
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: elastic_password
        volumeMounts:
        - name: setup-scripts
          mountPath: /setup
      restartPolicy: Never
      volumes:
      - name: setup-scripts
        configMap:
          name: setup-scripts
  backoffLimit: 4
