name: Test ELK Stack Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-elk-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove conflicting packages
        run: |
          for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove -y $pkg; done

      - name: Install Docker dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

      - name: Add Docker repository and install Docker
        run: |
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube /usr/local/bin/

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Start Minikube with Docker driver
        run: |
          sudo minikube start --driver=docker --force

      - name: Set up kubectl context
        run: |
          sudo minikube kubectl -- config use-context minikube

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/option-2-kubectl/

      - name: Verify ELK stack deployment
        run: |
          kubectl rollout status statefulset/elasticsearch
          kubectl rollout status deployment/kibana
          kubectl rollout status deployment/logstash

      - name: Forward Kibana port
        run: |
          kubectl port-forward service/kibana 5601:5601 &
          sleep 10

      - name: Test Kibana UI is accessible
        run: |
          curl -I http://localhost:5601

      - name: Clean up
        run: |
          kubectl delete -f kubernetes/option-2-kubectl/
          sudo minikube delete
